// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.2
// source: proto/connections.proto

package connections

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connections_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connections_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_connections_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type MyPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Lane string `protobuf:"bytes,2,opt,name=lane,proto3" json:"lane,omitempty"`
}

func (x *MyPosition) Reset() {
	*x = MyPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connections_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyPosition) ProtoMessage() {}

func (x *MyPosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connections_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyPosition.ProtoReflect.Descriptor instead.
func (*MyPosition) Descriptor() ([]byte, []int) {
	return file_proto_connections_proto_rawDescGZIP(), []int{1}
}

func (x *MyPosition) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MyPosition) GetLane() string {
	if x != nil {
		return x.Lane
	}
	return ""
}

type PositionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lane1 string `protobuf:"bytes,1,opt,name=lane1,proto3" json:"lane1,omitempty"`
	Lane2 string `protobuf:"bytes,2,opt,name=lane2,proto3" json:"lane2,omitempty"`
	Lane3 string `protobuf:"bytes,3,opt,name=lane3,proto3" json:"lane3,omitempty"`
	Lane4 string `protobuf:"bytes,4,opt,name=lane4,proto3" json:"lane4,omitempty"`
}

func (x *PositionInfo) Reset() {
	*x = PositionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_connections_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfo) ProtoMessage() {}

func (x *PositionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connections_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfo.ProtoReflect.Descriptor instead.
func (*PositionInfo) Descriptor() ([]byte, []int) {
	return file_proto_connections_proto_rawDescGZIP(), []int{2}
}

func (x *PositionInfo) GetLane1() string {
	if x != nil {
		return x.Lane1
	}
	return ""
}

func (x *PositionInfo) GetLane2() string {
	if x != nil {
		return x.Lane2
	}
	return ""
}

func (x *PositionInfo) GetLane3() string {
	if x != nil {
		return x.Lane3
	}
	return ""
}

func (x *PositionInfo) GetLane4() string {
	if x != nil {
		return x.Lane4
	}
	return ""
}

var File_proto_connections_proto protoreflect.FileDescriptor

var file_proto_connections_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22,
	0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x30,
	0x0a, 0x0a, 0x4d, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x61, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x65,
	0x22, 0x66, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x6e, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x32, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x6e, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e,
	0x65, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x65, 0x34, 0x32, 0x9b, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x10,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_connections_proto_rawDescOnce sync.Once
	file_proto_connections_proto_rawDescData = file_proto_connections_proto_rawDesc
)

func file_proto_connections_proto_rawDescGZIP() []byte {
	file_proto_connections_proto_rawDescOnce.Do(func() {
		file_proto_connections_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_connections_proto_rawDescData)
	})
	return file_proto_connections_proto_rawDescData
}

var file_proto_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_connections_proto_goTypes = []interface{}{
	(*Message)(nil),      // 0: chat.Message
	(*MyPosition)(nil),   // 1: chat.MyPosition
	(*PositionInfo)(nil), // 2: chat.PositionInfo
}
var file_proto_connections_proto_depIdxs = []int32{
	0, // 0: chat.Connections.SayHello:input_type -> chat.Message
	0, // 1: chat.Connections.Connected:input_type -> chat.Message
	1, // 2: chat.Connections.Positions:input_type -> chat.MyPosition
	0, // 3: chat.Connections.SayHello:output_type -> chat.Message
	0, // 4: chat.Connections.Connected:output_type -> chat.Message
	2, // 5: chat.Connections.Positions:output_type -> chat.PositionInfo
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_connections_proto_init() }
func file_proto_connections_proto_init() {
	if File_proto_connections_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_connections_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connections_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_connections_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_connections_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connections_proto_goTypes,
		DependencyIndexes: file_proto_connections_proto_depIdxs,
		MessageInfos:      file_proto_connections_proto_msgTypes,
	}.Build()
	File_proto_connections_proto = out.File
	file_proto_connections_proto_rawDesc = nil
	file_proto_connections_proto_goTypes = nil
	file_proto_connections_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ConnectionsClient is the client API for Connections service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionsClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Connected(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Positions(ctx context.Context, in *MyPosition, opts ...grpc.CallOption) (*PositionInfo, error)
}

type connectionsClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectionsClient(cc grpc.ClientConnInterface) ConnectionsClient {
	return &connectionsClient{cc}
}

func (c *connectionsClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.Connections/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionsClient) Connected(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.Connections/Connected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionsClient) Positions(ctx context.Context, in *MyPosition, opts ...grpc.CallOption) (*PositionInfo, error) {
	out := new(PositionInfo)
	err := c.cc.Invoke(ctx, "/chat.Connections/Positions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionsServer is the server API for Connections service.
type ConnectionsServer interface {
	SayHello(context.Context, *Message) (*Message, error)
	Connected(context.Context, *Message) (*Message, error)
	Positions(context.Context, *MyPosition) (*PositionInfo, error)
}

// UnimplementedConnectionsServer can be embedded to have forward compatible implementations.
type UnimplementedConnectionsServer struct {
}

func (*UnimplementedConnectionsServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedConnectionsServer) Connected(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connected not implemented")
}
func (*UnimplementedConnectionsServer) Positions(context.Context, *MyPosition) (*PositionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Positions not implemented")
}

func RegisterConnectionsServer(s *grpc.Server, srv ConnectionsServer) {
	s.RegisterService(&_Connections_serviceDesc, srv)
}

func _Connections_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Connections/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connections_Connected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServer).Connected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Connections/Connected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServer).Connected(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connections_Positions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyPosition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionsServer).Positions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Connections/Positions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionsServer).Positions(ctx, req.(*MyPosition))
	}
	return interceptor(ctx, in, info, handler)
}

var _Connections_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Connections",
	HandlerType: (*ConnectionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Connections_SayHello_Handler,
		},
		{
			MethodName: "Connected",
			Handler:    _Connections_Connected_Handler,
		},
		{
			MethodName: "Positions",
			Handler:    _Connections_Positions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/connections.proto",
}
